version: "3.8"

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - API_KEY=your_api_key
      - API_SECRET=your_api_secret
      - BASE_URL=https://api.gemini.com/v1
    volumes:
      - .:/app
